
version: '2'

services:
  export-pg:
    image: 'terrabrasilis/export-pg-data:v1.0.3'
    container_name: export-pg
    restart: "no"
    volumes:
      - '/main/storage/export-pg:/data'
    networks:
      - proxy_default

networks:
  proxy_default:
    external: true